[package]
name = "py_numass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "py_numass"
crate-type = ["cdylib"]

[dependencies]
processing = { git = "ssh://git@bitbucket.org/Kapot/numass-processing", tag = "0.1.0" }
numass = { git = "ssh://git@bitbucket.org/Kapot/dataforge-parser-numass.git", tag = "0.1.1" }
protobuf = "3.2.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pyo3 = { version = "0.18.0", features = ["extension-module"] }
numpy = "0.18.0"