[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[project]
name = "py_numass"
requires-python = ">=3.11"


[tool.poetry]
name = "py-numass"
version = "0.1.0"
description = ""
authors = ["chernov <kapot65@gmail.com>"]
# readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
dfparser = {git = "https://github.com/kapot65/python-df-parser"}
ipython = "^8.10.0"

