[workspace]
resolver = "2"
members = [
  "apps",
  # "analysis",
  "tqdc"
]

[workspace.dependencies]

log = "0.4.20"

tokio = { version = "1.21.2", features = ["full"] }
dataforge = { git = "https://bitbucket.org/Kapot/dataforge-parser-rust.git", tag = "0.1.2", features = ["tokio"]  }
processing = { git = "https://bitbucket.org/Kapot/numass-processing.git", features = ["egui"], tag = "0.1.2" }
eframe = "0.22.0"
clap = { version = "4.0.26", features = ["derive"] }
protobuf = "3.2.0"

serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.91"

[patch."https://bitbucket.org/Kapot/dataforge-parser-rust.git"]
dataforge = { path = "../dataforge-parser-rust" }

[patch."https://bitbucket.org/Kapot/numass-processing.git"]
processing = { path = "../numass-processing" }