[workspace]
resolver = "2"
members = [
  "apps",
  "tqdc"
]

[workspace.dependencies]

log = "0.4.20"
tokio = { version = "1.21.2", features = ["full"] }
dataforge = { git = "https://github.com/kapot65/dataforge-parser-rust.git", features = ["tokio"]  }
processing = { git = "https://github.com/kapot65/numass-processing.git", features = ["egui"] }
eframe = "0.31.1"
clap = { version = "4.0.26", features = ["derive"] }
protobuf = "3.7.1"

serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.91"

[patch."https://github.com/kapot65/dataforge-parser-rust.git"]
dataforge = { path = "../dataforge-parser-rust" }

[patch."https://github.com/kapot65/numass-processing.git"]
processing = { path = "../numass-processing" }