[package]
name = "processing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dataforge = {path = "../dataforge"}

tokio = { version = "1.21.2", features = ["full"] }
protobuf = "3.2.0"

plotters = "0.3.1"
plotly = "0.8.3"
