[package]
name = "processing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.152"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
eframe = "0.19.0"
serde_json = "1.0.91"

tokio = { version = "1.21.2", features = ["full"] }
protobuf = "3.2.0"
numass = { git = "ssh://git@bitbucket.org/Kapot/dataforge-parser-numass.git", tag = "0.1.1" }
dataforge = { git = "ssh://git@bitbucket.org/Kapot/dataforge-parser-rust.git", tag = "0.1.1", features = ["tokio"]  }

linreg = "0.2.0"

plotters = "0.3.1"
plotly = "0.8.3"
