[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tqdc = {path = "../tqdc"}
dataforge = {path = "../dataforge"}
time = "0.3.17"
tokio = { version = "1.21.2", features = ["full"] }

tokio-timerfd = "0.2.0"
protobuf = "3.2.0"
chrono = "0.4.23"

actix = "0.13.0"
actix-web = "4.2.1"
actix-web-lab = "0.18.5"
actix-web-actors = "4.1.0"
actix-files = "0.6.2"
