[package]
name = "apps"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(unix)'.dependencies]
tokio-timerfd = "0.2.0"

[dependencies]
tqdc = {path = "../tqdc"}

tokio = { workspace = true }
serde_json = { workspace = true }
dataforge = { workspace = true }
processing = { workspace = true }
eframe = { workspace = true }
clap = { workspace = true }
protobuf = { workspace = true }

chrono = "0.4.23"
home = "0.5.4"
eyre = "0.6.8"
battery = "0.7.8"
ssh2 = { version = "0.9.4", features = ["vendored-openssl"] }
