[package]
name = "apps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(unix)'.dependencies]
tokio-timerfd = "0.2.0"
rfd = "0.10.0"

[dependencies]
tqdc = {path = "../tqdc"}
numass = { git = "ssh://git@bitbucket.org/Kapot/dataforge-parser-numass.git", tag = "0.1.0" }
dataforge = { git = "ssh://git@bitbucket.org/Kapot/dataforge-parser-rust.git", tag = "0.1.0" }
processing = {path = "../processing"}

tokio = { version = "1.21.2", features = ["full"] }

protobuf = "3.2.0"
chrono = "0.4.23"
home = "0.5.4"
fs2 = "0.4.3"
plotly = "0.8.3"

serde_json = "1.0.88"
eyre = "0.6.8"

eframe = "0.19.0"
natord = "1.0.9"
clap = { version = "4.0.26", features = ["derive"] }
tinyfiledialogs = "3.9.1"

battery = "0.7.8"
